
ARG BASE_IMAGE_HASH="latest"
FROM wccyzxy/nango:${BASE_IMAGE_HASH}

ENV SERVER_RUN_MODE=DOCKERIZED

RUN true \
  && rm -rf packages/jobs \
  && rm -rf packages/runner \
  && rm -rf packages/persist

CMD ["packages/server/entrypoint.sh"]
